spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/fitness-oauth2/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userService
              uri: lb://USERSERVICE
              predicates:
                  - Path=/api/users/**

            - id: activityService
              uri: lb://ACTIVITYSERVICE
              predicates:
                - Path=/api/activities/**

            - id: aiService
              uri: lb://AISERVICE
              predicates:
                - Path=/api/recommendations/**


server:
  port: 8081

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

