spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_app_db
    username: postgres
    password: Sudha16*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
